# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CryptidsGame-App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: LukeRenton/CryptidsGame
          verbose: true

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: Get Short Commit SHA
        id: commit_sha
        run: echo ::set-output name=sha::$(git rev-parse --short HEAD)
  
      - name: Get Workflow Run ID
        id: workflow_run_id
        run: echo ::set-output name=run_id::${{ github.run_id }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA7B25CD1293446D836BCC8673E87748 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1FFDCDDA55746D4B90AD571333F8F7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_58A8079F290945EFAF90D5F4555CA5D3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CryptidsGame-App'
          slot-name: 'Production'
          package: .
 
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0-${{ steps.commit_sha.outputs.sha }} # Using the commit SHA for a unique tag
          release_name: 'Release v1.0.0 (Run ID: ${{ steps.workflow_run_id.outputs.run_id }})' # Using the workflow run ID for a unique release name
          body: 'Automated release with build and test results.'
          draft: false
          prerelease: false

      - name: Upload Artifact to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
          